### ISSUE TITLE
TODO: Need for organisation of links into sections

### ISSUE THREAD

**Issue by Spirizeon** [Spirizeon/OSPR#4]
There's a need for putting the links and references under titled sections.
like the following:

---
## Machine Learning
+ Link 1
+ Link 2 
## Containers
+ Docker link 1
---

**Comment by ReDxDaGer** [comment]
# Machine Learning 
+ [Machine learning for beginners](https://www.youtube.com/watch?v=Y4qO9unerGs&list=PLYwpaL_SFmcBhOEPwf5cFwqo5B-cP9G4P)
